_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -105.9851
  - 40.4469
  - 7
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - park
  - boundary
  - water
  - waterway
  - aeroway
  - building
  - transportation
  - place
  - poi
  - water_name
  - transportation_name
  - housenumber
maxzoom: 18
minzoom: 0
name: Positron Labels Only
source: "http://fast.nutiteq.com/v3.json"
styles: 
  - style.mss
  - labels.mss
template: ''
